jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Install-Scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run the install script
        run: ./install.sh
