name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '25 22 * * *' # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./Install-Scripts/install.sh

      - name: Run the script
        run: ./Install-Scripts/install.sh
